### ISSUE TITLE
SocketError: getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by loveshell** [kzk/webhdfs#7]
network is ok,and test connect webhdfs is error

```
[root@localhost ~]# nc -vv  192.168.1.122 50070
Connection to 192.168.1.122 50070 port [tcp/*] succeeded!
s
HTTP/1.1 400 Bad Request
Connection: close
Server: Jetty(6.1.26)
```

```
[root@localhost ~]# /usr/lib64/fluent/ruby/bin/irb
irb(main):001:0> require 'webhdfs'
=> true
irb(main):002:0> client = WebHDFS::Client.new('192.168.1.122','50070')
=> #<WebHDFS::Client:0x0000000127f7a8 @host="192.168.1.122", @port="50070", @username=nil, @doas=nil, @proxy_address=nil, @proxy_port=nil, @retry_known_errors=false, @retry_times=1, @retry_interval=1, @httpfs_mode=false>
irb(main):003:0> client.create('/test', 'data')
SocketError: getaddrinfo: Name or service not known
    from /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:763:in `initialize'
    from /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:763:in `open'
    from /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:763:in `block in connect'
    from /usr/lib64/fluent/ruby/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
    from /usr/lib64/fluent/ruby/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
    from /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:763:in `connect'
    from /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
    from /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:745:in `start'
    from /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:1285:in `request'
    from /usr/lib64/fluent/ruby/lib/ruby/1.9.1/net/http.rb:1265:in `send_request'
    from /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:281:in `request'
    from /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:242:in `operate_requests'
    from /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/webhdfs-0.5.5/lib/webhdfs/client_v1.rb:45:in `create'
    from (irb):3
    from /usr/lib64/fluent/ruby/bin/irb:12:in `<main>'
```

**Comment by IslamAzab** [comment]
@loveshell How did you solve that?
